default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  username: <%= ENV.fetch("USER") { '' } %>
  database: bigboss/development

test:
  <<: *default
  database: bigboss/test

production:
  <<: *default
  database: myapp
  username: myapp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>

