default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV.fetch("USER") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: bigboss/development

test:
  <<: *default
  database: bigboss/test

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>

